$axure.loadCurrentPage({
  "url":"horror.html",
  "generationDate":new Date(1668147753178.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7a371a6bf8d8476a8c1a911258c60899",
    "type":"Axure:Page",
    "name":"Horror",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a1f2ca91e754e1b99f27bb5260fcc4c",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":41.5},
            "size":{
              "width":600,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deed45a390834055b984849bbc2fc221",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e588081bdc64d21bba114b4eebbc7a0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a93aebb1bab54db1971a8fe94f6d8fd9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"b4ca6b11b9f54ac7afc87194daa00d3e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b29951ab60b5458f80cae92973ceceb8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Action in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"action.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"b24c67e89263411ebb2c46e4a95ee1aa",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ccca4a5c0cf4939ac69bd43dc001c2e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Comedy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"comedy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"396b5b189305490abf5baac42d8c15ed",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6849223484b94460839cf6af124e52c8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Horror in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"horror.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"24939b1e704e4e908cb7b21b2fad3b04",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66c7906f7dfd4363b4b048a307d70061",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Animation in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"animation.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"9445b44173024a2f82d96ed36a85d54c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3aaa6ea1227147539e24e058cbc42473",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Romance in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"romance.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u12.png"}}]}]},
{
          "id":"cfbcc379bf824d8da38cc2fc6ccc43b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed', 'Bernard MT'",
            "fontSize":"72px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "location":{
              "x":18,
              "y":0},
            "size":{
              "width":232,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0dfb0fd34614177bff4ffdbb11e033c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed', 'Bernard MT'",
                "fontSize":"72px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "location":{
                  "x":18,
                  "y":0},
                "size":{
                  "width":232,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f569e07a71074b9181347f38188b4c56",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Bodoni MT Poster Compressed Light', 'Bodoni MT Poster'",
            "fontSize":"72px",
            "fontWeight":"300",
            "horizontalAlignment":"center",
            "location":{
              "x":417,
              "y":100},
            "size":{
              "width":121,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e045210aad394d589d46f6c3fc1738d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bodoni MT Poster Compressed Light', 'Bodoni MT Poster'",
                "fontSize":"72px",
                "fontWeight":"300",
                "horizontalAlignment":"center",
                "location":{
                  "x":417,
                  "y":100},
                "size":{
                  "width":121,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12b0e3ff96e646b2a893b7b54a1eb498",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":526},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c3ac119b5ff4601a41221ef228b3853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":526},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"927020fc7905439aa9c6ef02b8c1f381",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":249},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70aff82e75e46adb75e5771719f9f0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":249},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt10403420/?ref_=nv_sr_srsg_0 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt10403420/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"e88b0fc9865843599310dd751744d4d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":526},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f34b6fbb8b4d45aca2ea9543232ea8a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":526},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db44727713ad4441beb06c688e64a2f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":246},
            "size":{
              "width":190,
              "height":277}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05f603406663455f8d8ff73e6c4446e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":246},
                "size":{
                  "width":190,
                  "height":277}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt7144666/?ref_=fn_al_tt_0 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt7144666/?ref_=fn_al_tt_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u66.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a1f2ca91e754e1b99f27bb5260fcc4c":{
      "scriptId":"u0"},
    "deed45a390834055b984849bbc2fc221":{
      "scriptId":"u1"},
    "1e588081bdc64d21bba114b4eebbc7a0":{
      "scriptId":"u2"},
    "a93aebb1bab54db1971a8fe94f6d8fd9":{
      "scriptId":"u3"},
    "b4ca6b11b9f54ac7afc87194daa00d3e":{
      "scriptId":"u4"},
    "b29951ab60b5458f80cae92973ceceb8":{
      "scriptId":"u5"},
    "b24c67e89263411ebb2c46e4a95ee1aa":{
      "scriptId":"u6"},
    "8ccca4a5c0cf4939ac69bd43dc001c2e":{
      "scriptId":"u7"},
    "396b5b189305490abf5baac42d8c15ed":{
      "scriptId":"u8"},
    "6849223484b94460839cf6af124e52c8":{
      "scriptId":"u9"},
    "24939b1e704e4e908cb7b21b2fad3b04":{
      "scriptId":"u10"},
    "66c7906f7dfd4363b4b048a307d70061":{
      "scriptId":"u11"},
    "9445b44173024a2f82d96ed36a85d54c":{
      "scriptId":"u12"},
    "3aaa6ea1227147539e24e058cbc42473":{
      "scriptId":"u13"},
    "cfbcc379bf824d8da38cc2fc6ccc43b3":{
      "scriptId":"u14"},
    "a0dfb0fd34614177bff4ffdbb11e033c":{
      "scriptId":"u15"},
    "f569e07a71074b9181347f38188b4c56":{
      "scriptId":"u16"},
    "e045210aad394d589d46f6c3fc1738d3":{
      "scriptId":"u17"},
    "12b0e3ff96e646b2a893b7b54a1eb498":{
      "scriptId":"u18"},
    "9c3ac119b5ff4601a41221ef228b3853":{
      "scriptId":"u19"},
    "927020fc7905439aa9c6ef02b8c1f381":{
      "scriptId":"u20"},
    "d70aff82e75e46adb75e5771719f9f0b":{
      "scriptId":"u21"},
    "e88b0fc9865843599310dd751744d4d7":{
      "scriptId":"u22"},
    "f34b6fbb8b4d45aca2ea9543232ea8a9":{
      "scriptId":"u23"},
    "db44727713ad4441beb06c688e64a2f0":{
      "scriptId":"u24"},
    "05f603406663455f8d8ff73e6c4446e5":{
      "scriptId":"u25"}}});