$axure.loadCurrentPage({
  "url":"animation.html",
  "generationDate":new Date(1668147753304.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e12802d77214f2181f66f1402fd958c",
    "type":"Axure:Page",
    "name":"Animation",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3cfbecbeda84e7dbcb346e56353d3cc",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":41.5},
            "size":{
              "width":600,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55a5bd54cce6461ab68c6bc8cc55d57a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67ea5fc234fb4f7ba293f43aca993f5a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c81ee0bdb4d4d2d814c765b86925d76",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"9f4ed63ab6f54d7e912065e725207780",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0a89a6fdb6844dbb8fe304b46d45f68",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Action in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"action.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"98ac0d8c5aa34aff97c73887c119bce6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29d7b8e244514847a2dc7ee57830de0d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Comedy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"comedy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"9c2b218fc06a48ad92268b4e742f7460",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b82cd1378d548db9fd22e98c2b74046",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Horror in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"horror.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"3dead549111549b8bebe3afc858663a0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b53d47bc2d64b22bc358e30dd9d1871",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Animation in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"animation.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"1aeed7b8956c46828b61ab46a64a5dc1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f0ef11cb1d0e41b6bfc935761f612db1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Romance in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"romance.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u12.png"}}]}]},
{
          "id":"68e2a374a7bd455b8a838a8efa40ffe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed', 'Bernard MT'",
            "fontSize":"72px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "location":{
              "x":18,
              "y":0},
            "size":{
              "width":232,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35d1575b581c4577905d9caeb7838a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed', 'Bernard MT'",
                "fontSize":"72px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "location":{
                  "x":18,
                  "y":0},
                "size":{
                  "width":232,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f16f445c757f4d4ba90454e36b406fff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Pristina Oblique', 'Pristina'",
            "fontSize":"72px",
            "fontStyle":"oblique",
            "location":{
              "x":417,
              "y":91},
            "size":{
              "width":310,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4be15ce799c44e3a3068953bd1f5866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Pristina Oblique', 'Pristina'",
                "fontSize":"72px",
                "fontStyle":"oblique",
                "location":{
                  "x":417,
                  "y":91},
                "size":{
                  "width":310,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaf518e3478b4830aa386bef24173db8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":250},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa14855dba924dc585d5b91d925b1d33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":250},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt9848626/?ref_=fn_al_tt_1 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt9848626/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"88c60d993fc1467299f22c8d5ab88052",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":526},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a09ad3bab7b4ff8ba5f471e16c4c7c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":526},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b3cfbecbeda84e7dbcb346e56353d3cc":{
      "scriptId":"u0"},
    "55a5bd54cce6461ab68c6bc8cc55d57a":{
      "scriptId":"u1"},
    "67ea5fc234fb4f7ba293f43aca993f5a":{
      "scriptId":"u2"},
    "7c81ee0bdb4d4d2d814c765b86925d76":{
      "scriptId":"u3"},
    "9f4ed63ab6f54d7e912065e725207780":{
      "scriptId":"u4"},
    "b0a89a6fdb6844dbb8fe304b46d45f68":{
      "scriptId":"u5"},
    "98ac0d8c5aa34aff97c73887c119bce6":{
      "scriptId":"u6"},
    "29d7b8e244514847a2dc7ee57830de0d":{
      "scriptId":"u7"},
    "9c2b218fc06a48ad92268b4e742f7460":{
      "scriptId":"u8"},
    "3b82cd1378d548db9fd22e98c2b74046":{
      "scriptId":"u9"},
    "3dead549111549b8bebe3afc858663a0":{
      "scriptId":"u10"},
    "1b53d47bc2d64b22bc358e30dd9d1871":{
      "scriptId":"u11"},
    "1aeed7b8956c46828b61ab46a64a5dc1":{
      "scriptId":"u12"},
    "f0ef11cb1d0e41b6bfc935761f612db1":{
      "scriptId":"u13"},
    "68e2a374a7bd455b8a838a8efa40ffe7":{
      "scriptId":"u14"},
    "35d1575b581c4577905d9caeb7838a88":{
      "scriptId":"u15"},
    "f16f445c757f4d4ba90454e36b406fff":{
      "scriptId":"u16"},
    "f4be15ce799c44e3a3068953bd1f5866":{
      "scriptId":"u17"},
    "eaf518e3478b4830aa386bef24173db8":{
      "scriptId":"u18"},
    "fa14855dba924dc585d5b91d925b1d33":{
      "scriptId":"u19"},
    "88c60d993fc1467299f22c8d5ab88052":{
      "scriptId":"u20"},
    "9a09ad3bab7b4ff8ba5f471e16c4c7c7":{
      "scriptId":"u21"}}});