$axure.loadCurrentPage({
  "url":"romance.html",
  "generationDate":new Date(1668147753360.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f370ca00b6e44c4689a2eb769390f002",
    "type":"Axure:Page",
    "name":"Romance",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"61a1db40a3a94a42a4b7df15e859806a",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":41.5},
            "size":{
              "width":600,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a9b4dcff4a46b2ad3fddf4f1443b8f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91969011177b4cbc93f813000218350f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4ab3f9217b74b31bdd690f14f79746b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"3c917e7f14234589a3b861418db15d3d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce5bb07911b149d9b4a5bd11ea2b083c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Action in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"action.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"ecdfe9fc941d4f0c9799f142d3bdfe5c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"921038bd7ed441459bb8f89c1376537c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Comedy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"comedy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"823618e25eff42f380fbaaa7adae711b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ebfd9474bfb4064b2a27d59a13f9426",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Horror in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"horror.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"71f3181fe4be4a0b8103e6bba3e5c903",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab4fbc83955e46d596cef07c0eab1b77",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Animation in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"animation.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"9810c148334144edb2d2a75e68648698",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f577c26d51e4078b7b4070c122ce92c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Romance in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"romance.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u12.png"}}]}]},
{
          "id":"d2348bc43367413ea31d7226cdd3f1d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed', 'Bernard MT'",
            "fontSize":"72px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "location":{
              "x":18,
              "y":0},
            "size":{
              "width":232,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b031a8b4f4244fc8f4d16087c4e7047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed', 'Bernard MT'",
                "fontSize":"72px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "location":{
                  "x":18,
                  "y":0},
                "size":{
                  "width":232,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79c584d9be5f4e5ca3ce1940bd8ecc0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Kunstler Script Bold', 'Kunstler Script'",
            "fontSize":"72px",
            "fontWeight":"700",
            "location":{
              "x":411,
              "y":100},
            "size":{
              "width":220,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e8f419f7ad42b9bc2cf56183e96d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Kunstler Script Bold', 'Kunstler Script'",
                "fontSize":"72px",
                "fontWeight":"700",
                "location":{
                  "x":411,
                  "y":100},
                "size":{
                  "width":220,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d4963d0387f4097a016ad0980ffacf1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":250},
            "size":{
              "width":190,
              "height":274}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b8b8c6fa2ea48a5aadb476c057393a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":250},
                "size":{
                  "width":190,
                  "height":274}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt11365186/?ref_=fn_al_tt_1 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt11365186/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u40.png"}},
{
          "id":"79b426f9ec3f4a54943f7e82fe06d1a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":528},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a03c418374a4825b30c9e20736c1711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":528},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06fe60ce6cf842e7b699f0ca3fd1cb4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":529},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967c141affd94087a1ee8a3ea479c460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":529},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de723e279e04098ba55863ee7c4c854",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":250},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de72b61ce0d0442d91cbe1a68e7d2431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":250},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt1655389/?ref_=fn_al_tt_1 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt1655389/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u52.png"}},
{
          "id":"0b848a8fb41e4f039a1b68bc591a6d09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":558,
              "y":529},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ef8b7e805a542cca7dd8d28e0bcef10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":558,
                  "y":529},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"708f5cea202f4fd2b7988f791519a099",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":250},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16248492c1354a33940b403941be1b58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":524,
                  "y":250},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt12996154/?ref_=fn_al_tt_1 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt12996154/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u56.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "61a1db40a3a94a42a4b7df15e859806a":{
      "scriptId":"u0"},
    "75a9b4dcff4a46b2ad3fddf4f1443b8f":{
      "scriptId":"u1"},
    "91969011177b4cbc93f813000218350f":{
      "scriptId":"u2"},
    "e4ab3f9217b74b31bdd690f14f79746b":{
      "scriptId":"u3"},
    "3c917e7f14234589a3b861418db15d3d":{
      "scriptId":"u4"},
    "ce5bb07911b149d9b4a5bd11ea2b083c":{
      "scriptId":"u5"},
    "ecdfe9fc941d4f0c9799f142d3bdfe5c":{
      "scriptId":"u6"},
    "921038bd7ed441459bb8f89c1376537c":{
      "scriptId":"u7"},
    "823618e25eff42f380fbaaa7adae711b":{
      "scriptId":"u8"},
    "5ebfd9474bfb4064b2a27d59a13f9426":{
      "scriptId":"u9"},
    "71f3181fe4be4a0b8103e6bba3e5c903":{
      "scriptId":"u10"},
    "ab4fbc83955e46d596cef07c0eab1b77":{
      "scriptId":"u11"},
    "9810c148334144edb2d2a75e68648698":{
      "scriptId":"u12"},
    "6f577c26d51e4078b7b4070c122ce92c":{
      "scriptId":"u13"},
    "d2348bc43367413ea31d7226cdd3f1d8":{
      "scriptId":"u14"},
    "0b031a8b4f4244fc8f4d16087c4e7047":{
      "scriptId":"u15"},
    "79c584d9be5f4e5ca3ce1940bd8ecc0b":{
      "scriptId":"u16"},
    "07e8f419f7ad42b9bc2cf56183e96d25":{
      "scriptId":"u17"},
    "8d4963d0387f4097a016ad0980ffacf1":{
      "scriptId":"u18"},
    "3b8b8c6fa2ea48a5aadb476c057393a2":{
      "scriptId":"u19"},
    "79b426f9ec3f4a54943f7e82fe06d1a8":{
      "scriptId":"u20"},
    "7a03c418374a4825b30c9e20736c1711":{
      "scriptId":"u21"},
    "06fe60ce6cf842e7b699f0ca3fd1cb4b":{
      "scriptId":"u22"},
    "967c141affd94087a1ee8a3ea479c460":{
      "scriptId":"u23"},
    "2de723e279e04098ba55863ee7c4c854":{
      "scriptId":"u24"},
    "de72b61ce0d0442d91cbe1a68e7d2431":{
      "scriptId":"u25"},
    "0b848a8fb41e4f039a1b68bc591a6d09":{
      "scriptId":"u26"},
    "4ef8b7e805a542cca7dd8d28e0bcef10":{
      "scriptId":"u27"},
    "708f5cea202f4fd2b7988f791519a099":{
      "scriptId":"u28"},
    "16248492c1354a33940b403941be1b58":{
      "scriptId":"u29"}}});