$axure.loadCurrentPage({
  "url":"comedy.html",
  "generationDate":new Date(1668147753098.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"444a13241cc44fb5a737b7117a14a8d2",
    "type":"Axure:Page",
    "name":"Comedy",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cf18f194d20c4827be6e8bcb4dd79a46",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":41.5},
            "size":{
              "width":600,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e1e1997b25441ba2f64b136ecb2c4a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd6fa32bb3ca4c85b63480cf51ae4d0e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a047ebfd5f884a078cd70194ef9ab2f9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"a361fc63590741e1ac0181986c49ba61",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd444ce1279f4ed293112c7b1f863174",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Action in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"action.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"69a2c7ed9c7c4300851c633270b1b429",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b684d9abf7c438cb443e66fc951f6da",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Comedy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"comedy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"8e2dfcbcd33441fe8d53a8a636288316",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c83216d195da4906886f171b7b6b12c8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Horror in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"horror.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"29a2b207e95b4dc6b15696b622df3e95",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d413459681a469d9a6aae3da30d37e2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Animation in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"animation.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u2.png"}},
{
                  "id":"67d32019792d4e18a844bf7b94511b4c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"839af8deff094faaab2df07703a08ad0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Romance in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"romance.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u12.png"}}]}]},
{
          "id":"0ab7223a96034f3a9f1a608f2b4a42b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed', 'Bernard MT'",
            "fontSize":"72px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "location":{
              "x":18,
              "y":0},
            "size":{
              "width":232,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8118d359573a43ec8b1a0a61705038bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed', 'Bernard MT'",
                "fontSize":"72px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "location":{
                  "x":18,
                  "y":0},
                "size":{
                  "width":232,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e93244f4c4d49d8a91a14ba3c12692b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Gigi Bold', 'Gigi'",
            "fontSize":"72px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":382,
              "y":100},
            "size":{
              "width":290,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a51ca8df32e4b02a170d6a8d101a32d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Gigi Bold', 'Gigi'",
                "fontSize":"72px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":382,
                  "y":100},
                "size":{
                  "width":290,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e43c7d15477c43f1b8fdc26effa26774",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":539},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d9d45e84b9e403a83f48d92076af5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":539},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"603e9cf16bca4ac6810c0365c7596f45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":260},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8714c323f20a40ae9b95303ce751c2ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":260},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt10268488/?ref_=fn_al_tt_1 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt10268488/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u60.png"}},
{
          "id":"10cbf6896d7e4137923908c504fef89e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":539},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb3c5de812f459ca35e67ea36059664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":356,
                  "y":539},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dec6f488de6c40318eb13406b7992ed5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":260},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1753faba1e064cafa2714595600550a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":260},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt14309446/?ref_=nv_sr_srsg_0 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt14309446/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u64.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cf18f194d20c4827be6e8bcb4dd79a46":{
      "scriptId":"u0"},
    "65e1e1997b25441ba2f64b136ecb2c4a":{
      "scriptId":"u1"},
    "dd6fa32bb3ca4c85b63480cf51ae4d0e":{
      "scriptId":"u2"},
    "a047ebfd5f884a078cd70194ef9ab2f9":{
      "scriptId":"u3"},
    "a361fc63590741e1ac0181986c49ba61":{
      "scriptId":"u4"},
    "fd444ce1279f4ed293112c7b1f863174":{
      "scriptId":"u5"},
    "69a2c7ed9c7c4300851c633270b1b429":{
      "scriptId":"u6"},
    "0b684d9abf7c438cb443e66fc951f6da":{
      "scriptId":"u7"},
    "8e2dfcbcd33441fe8d53a8a636288316":{
      "scriptId":"u8"},
    "c83216d195da4906886f171b7b6b12c8":{
      "scriptId":"u9"},
    "29a2b207e95b4dc6b15696b622df3e95":{
      "scriptId":"u10"},
    "9d413459681a469d9a6aae3da30d37e2":{
      "scriptId":"u11"},
    "67d32019792d4e18a844bf7b94511b4c":{
      "scriptId":"u12"},
    "839af8deff094faaab2df07703a08ad0":{
      "scriptId":"u13"},
    "0ab7223a96034f3a9f1a608f2b4a42b1":{
      "scriptId":"u14"},
    "8118d359573a43ec8b1a0a61705038bc":{
      "scriptId":"u15"},
    "3e93244f4c4d49d8a91a14ba3c12692b":{
      "scriptId":"u16"},
    "0a51ca8df32e4b02a170d6a8d101a32d":{
      "scriptId":"u17"},
    "e43c7d15477c43f1b8fdc26effa26774":{
      "scriptId":"u18"},
    "3d9d45e84b9e403a83f48d92076af5cf":{
      "scriptId":"u19"},
    "603e9cf16bca4ac6810c0365c7596f45":{
      "scriptId":"u20"},
    "8714c323f20a40ae9b95303ce751c2ee":{
      "scriptId":"u21"},
    "10cbf6896d7e4137923908c504fef89e":{
      "scriptId":"u22"},
    "4cb3c5de812f459ca35e67ea36059664":{
      "scriptId":"u23"},
    "dec6f488de6c40318eb13406b7992ed5":{
      "scriptId":"u24"},
    "1753faba1e064cafa2714595600550a3":{
      "scriptId":"u25"}}});